AWSTemplateFormatVersion: 2010-09-09
Description: Bucket Creation
Resources:
  ProjectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "smarthrcrm"
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProjectBucket
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::smarthrcrm/*"
            }
          ]
        }