Resources:
  EmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const sns = new AWS.SNS();

          exports.handler = async (event) => {
            const email = event.email;
            const message = event.message;
            const params = {
              Destination: {
                ToAddresses: [email]
              },
              Message: {
                Body: {
                  Text: {
                    Data: message
                  }
                },
                Subject: {
                  Data: 'New message from your website'
                }
              },
              Source: 'your_sender_email_address'
            };

            try {
              await new AWS.SES({ apiVersion: '2010-12-01' }).sendEmail(params).promise();
              console.log(`Email sent to ${email}`);
            } catch (err) {
              console.log(err);
            }
          }
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 30

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-email-api

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: email

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmailFunction.Arn}/invocations
        IntegrationResponses:
        - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway

Outputs:
  ApiEndpoint:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/email"
